version: '3.7'

services:
  database:
    image: usdotfhwaops/v2x-mariadb:v1.0
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: IVP
      MYSQL_USER: IVP
      MYSQL_PASSWORD: ivp
      MYSQL_ROOT_PASSWORD: ivp
    network_mode: host
    volumes:
      - "mysql_data:/var/lib/mysql"
      - ./mysql/amd64.sql:/docker-entrypoint-initdb.d/amd64.sql

  php:
    image: php:7.2.2-apache
    container_name: php
    volumes:
      - ./php/:/var/www/html/
    network_mode: host
    restart: always
    depends_on: 
      - database
    stdin_open: true
    tty: true

  v2xhubarm:
    image: usdotfhwaops/v2x-hub-arm:v4.0
    container_name: v2xhubarm
    network_mode: host
    restart: always
    depends_on: 
      - php
    volumes:
      - "logs:/var/log/tmx"

volumes:
    mysql_data:
    logs:
